
start_urls = []

MASTER_MYSQL_HOST = '127.0.0.1'
MASTER_MYSQL_PORT = 3306
MASTER_MYSQL_USER = 'root'
MASTER_MYSQL_PASSWORD = '123456'
MASTER_MYSQL_DATABASE = 'sina'
MASTER_MYSQL_USER_TABLE = 'userinfo'
MASTER_MYSQL_ARTICLA_TABLE = 'ArticalInfo'
MASTER_MYSQL_COMMIT_TABLE = 'CommitInfo'


LOCAL_REDIS_HOST = '127.0.0.1'            #'155.138.229.23'
LOCAL_REDIS_PORT = 6379
LOCAL_REDIS_PASSWORD = None  #'123456'


MASTER_REQUEST_QUEUE = 'Sina_master:request_queue'
MASTER_NEW_REQUEST_QUEUE = 'Sina_master:new_request_queue'
MASTER_DEPUFILTER_QUEUE = 'Sina_master:depufilter_queue'


SLAVER_REQUEST_QUEUE = 'Sina_slaver:request_queue'
SLAVER_1_NAME = ''
SLAVER_1_REDIS_HOST = ''
SLAVER_1_REDIS_PORT = ''
SLAVER_1_REDIS_PASSWORD = ''

SLAVER_2_NAME = ''
SLAVER_2_REDIS_HOST = ''
SLAVER_2_REDIS_PORT = ''
SLAVER_2_REDIS_PASSWORD = ''


TIMEOUT = 10




